spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
custom:
  feign:
    url:
      deal: 'http://deal:8080/deal'
  message:
    finish-registration:
      subject: "Finish registration in credit-conveyor"
      text: "Hello, your loan application 邃本applicationId} approved! \nNow you should finish registration by the following link: http://localhost:8080/swagger-ui/index.html#/application/finishRegistration"
    create-document:
      subject: "Create documents for your loan application"
      text: "Hello, your loan application 邃本applicationId} passed all checks! \nNow you should send creating documents request by the following link: http://localhost:8080/swagger-ui/index.html#/document/createDocuments"
    send-document:
      subject: "Your loan documents"
      text: "Hello, here it is your loan documents for application 邃本applicationId}! \nNow you should send signing documents request by the following link: http://localhost:8080/swagger-ui/index.html#/document/signDocuments"
    send-ses:
      subject: "Your Simple Electric Sign"
      text: "Hello, here it is your Simple Electric Sign code {sesCode} for your application 邃本applicationId}. \nNow you should send this code to: http://localhost:8080/swagger-ui/index.html#/document/sendSesCode"